name: Bug Report
description: Create a report to help us improve the Owen Animation System
title: "[Bug]: "
labels: ["bug", "needs-triage"]
projects: ["kjanat/Owen"]
assignees:
  - kjanat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible to help us understand and reproduce the issue.

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened instead?
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: dropdown
    id: animation-scheme
    attributes:
      label: Animation Naming Scheme
      description: Which animation naming scheme were you using when the bug occurred?
      options:
        - Legacy
        - Artist
        - Hierarchical
        - Semantic
        - Multiple schemes
        - Not applicable
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Where did you encounter this bug?
      options:
        - Browser (Web)
        - Node.js
        - React integration
        - Vue integration
        - Blender integration
        - Demo application
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: browser-info
    attributes:
      label: Browser/Runtime Information
      description: If applicable, provide browser or runtime version information
      placeholder: |
        - Browser: Chrome 91.0
        - Node.js: v18.17.0
        - OS: Windows 11
        - Owen Animation System: v1.2.3

  - type: textarea
    id: code-sample
    attributes:
      label: Code Sample
      description: If applicable, provide a minimal code sample that reproduces the issue
      render: javascript
      placeholder: |
        ```javascript
        import { AnimationNameMapper } from 'owen-animation-system';

        const mapper = new AnimationNameMapper();
        // Your code that demonstrates the issue
        ```

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission checklist
      description: Please verify the following before submitting
      options:
        - label: I have searched existing issues to make sure this is not a duplicate
          required: true
        - label: I have provided a clear and concise description of the bug
          required: true
        - label: I have included steps to reproduce the issue
          required: true
